Third iteration
ironhird/YP-go-fitness-tracker pull request #3
Opened 2024-10-09 14:04 UTC by ironhird

2024-10-09 15:47 UTC, just-musha requested changes
Привет! По формулам все ок, единственное - нужно отформатировать код. И работа будет принята.

2024-10-09 15:47 UTC, just-musha commented on ftracker.go
> +    heightMeters := height /100
Вместо 100 стоит использовать специальную константу

2024-10-09 15:47 UTC, just-musha commented on ftracker.go
> +    res := runningCaloriesMeanSpeedMultiplier * meanSpeed(action, duration) * runningCaloriesMeanSpeedShift
Отступы разные в файле - стоит запустить `go fmt` и отформатировать код

Рекомендую сразу его прописать в настройках IDE в автозапуск при сохранении

2024-10-09 22:19 UTC, ironhird commented on ftracker.go
> +    heightMeters := height /100
Заменил 100 на cmInM

2024-10-09 22:21 UTC, ironhird commented on ftracker.go
> +    res := runningCaloriesMeanSpeedMultiplier * meanSpeed(action, duration) * runningCaloriesMeanSpeedShift
Отформатировал автоматически. Путём ручного сохранения файла (Ctrl+S). Отключил в IDE функцию AutoSave потому что она не запускает форматирование.

2024-10-10 05:43 UTC, ironhird commented
Нужно ли создать новый PR?

2024-10-12 06:55 UTC, ironhird commented
> Нужно ли создать новый PR?

`После того как вы исправите код с учётом комментариев ревьюера, не забудьте закоммитить изменения. Новый коммит появится в Pull Request, и вы сможете отправить работу на повторную проверку.`

2024-10-12 17:10 UTC, just-musha commented
@ironhird привет! Все верно, новый ПР не нужен, тк удобно когда все комментарии и правки в одном ПРе, видно историю комментариев и т.д

2024-10-12 17:10 UTC, just-musha approved these changes
Супер, принято!

2024-10-16 00:46 UTC, merged